[[main]]
name = "Blog"
pageRef = "blog"
identifier = "gFCo2i677J"
weight = 9999

[[main]]
name = "About"
pageRef = "about"
identifier = "woBKqfGKC5"
weight = 9999

[[main]]
name = "Photos"
pageRef = "photos"
identifier = "yS11aKwCyc"
weight = 9999

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10
