---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy-to-cloudpanel
    image: debian:stable-slim
    environment:
      DEPLOY_KEY:
        from_secret: DEPLOY_KEY
      DEPLOY_USER:
        from_secret: DEPLOY_USER
      SERVER_IP:
        from_secret: SERVER_IP
      git_http_url:
        from_secret: git_http_url
    commands:
      - apt-get -y update
      - apt-get -y install openssh-server
      - mkdir -p ~/.ssh/
      - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo $DRONE_REMOTE_URL
      - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$SERVER_IP "cd /home/nipunh/tmp && git clone --depth 1 $DRONE_REMOTE_URL && cd portfolio && rm -rf .* && cp -R . /home/nipunh/htdocs/nipunh.com/"
