---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy-to-cloudpanel
    image: linuxserver/openssh-server
    commands:
      - apk add --no-cache openssh
      - mkdir ~/.ssh/
      - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@192.168.50.200"
# cd /home/nipunh/tmp && git clone --depth 1 $git_http_url && cd portfolio
